### ISSUE TITLE
document "--no-XXX" handling 

### ISSUE THREAD

**Issue by micalevisk** [meszaros-lajos-gyorgy/minimist-lite#10]
Original issue by @getify at https://github.com/substack/minimist/issues/54

> I had to read the source code to diagnose why `--no-foobar` was not working as I expected (it wasn't giving me a `"--no-foobar": true` entry in my arguments. It was instead setting `"foobar": false`. Interesting feature, but should be documented.

**Comment by micalevisk** [comment]
I could take this one but I'm unsure on what's the best way to add this to the README

**Comment by meszaros-lajos-gyorgy** [comment]
On the topic of adding infos to the readme I see the following pull request: https://github.com/substack/minimist/pull/74
It doesn't solve the original issue, but this ticket would be a nice general ticket with the purpose of updating the readme.

**Comment by micalevisk** [comment]
~so I can create another branch just to address documentation issues and in a single PR. Sounds good to you? then you could commit on that branch as well~ nvm I just saw 4859e265d8e09efba044b1bad3a47269d60776df
