### ISSUE TITLE
TypeScript Definitions Not Included in Package

### ISSUE THREAD

**Issue by jrkienle** [meszaros-lajos-gyorgy/minimist-lite#13]
Hey all!

Thanks for forking minimist, it's nice to see work being done on an abandoned project once more. I pulled this project into my application and noticed TypeScript was complaining saying `Could not find a declaration file for module 'minimist-lite'.` I saw that you have an `index.d.ts` in the repo and looked in the package itself to investigate. To my surprise, I saw that the `d.ts` wasn't included with the packaged module (see the attached screenshot for details)

<img width="171" alt="Screen Shot 2022-01-23 at 2 36 58 PM" src="https://user-images.githubusercontent.com/15018432/150700772-7ca20ac2-9919-4856-9745-34f002682701.png">

As a workaround I've created an empty `minimist-lite.d.ts` with the contents `declare module 'minimist-lite';`, but I know this isn't a sustainable route to take moving forward

**Comment by micalevisk** [comment]
this will be fixed in the next patch release. Thank you!
