### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [meszaros-lajos-gyorgy/minimist-lite#16]
@micalevisk whad do you think, is the current master ready to be released or is there anything else we can add? We could start creating version labels and add those to the individual tickets. I'll set up github projects page and we can add ideas there as well.

**Comment by meszaros-lajos-gyorgy** [comment]
Okay, I'm not delaying the release any further.

**Comment by micalevisk** [comment]
idk why didn't get notified about this lol sorry.

I'll use the github projects, I like it
