### ISSUE TITLE
Enable Dependabot security updates

### ISSUE THREAD

**Issue by micalevisk** [meszaros-lajos-gyorgy/minimist-lite#23]
@meszaros-lajos-gyorgy not sure if this is already enabled in this repo. The goal here is to have some bot that will open a PR with security patches

https://docs.github.com/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

**Comment by meszaros-lajos-gyorgy** [comment]
Hi! Sounds like a good idea, I've enabled it just now, let's see what it can do. The more tools to keep the repo green the better.
