### ISSUE TITLE
Auto converting hex values to numbers

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [meszaros-lajos-gyorgy/minimist-lite#5]
Original issue by @dimabru at https://github.com/substack/minimist/issues/149

`Hex` parameters get auto-converted to numbers.
This results in a loss of information and change of values since `hex` values often exceed max int.

example:
input args `--a 0xffffffffffffffffffff`

code:
`console.log(process.argv.slice(2));`
`let args = minimist(process.argv.slice(2));`
`console.log(args['a']);`
`console.log(args['a'].toString(16));`

console output:
![image](https://user-images.githubusercontent.com/2386064/147097743-63698ef3-9c57-44a6-93d5-18e61b1dd2b1.png)

`100000000000000000000` is clearly !== `0xffffffffffffffffffff`

**Comment by micalevisk** [comment]
I believe you can take the solution from this PR: https://github.com/substack/minimist/pull/150

**Comment by meszaros-lajos-gyorgy** [comment]
Added the fix and released a new version: https://github.com/meszaros-lajos-gyorgy/minimist-lite/releases/tag/v2.0.1
