### ISSUE TITLE
Proposal: Adding option for longer arguments names

### ISSUE THREAD

**Issue by 403-html** [meszaros-lajos-gyorgy/minimist-lite#6]
So I thought if we'd be able to add support for longer names (currently it supports only "one letter" arguments). I have small issue because I'd like to add longer arguments. Like

```
const argvs = require("minimist")(process.argv.slice(2));

console.log(argvs)

if (argvs.th || argvs.templateHelp) {
    templateHelp();
}

if (argvs.h || argvs.help) {
    help();
}
```

So when I call `node index.js -th`  this will call for `templateHelp()` function, not the `help()` one (because it divides arguments into argvs: `{ _: [], t: true, h: true }`)

**Comment by meszaros-lajos-gyorgy** [comment]
Hi! Sorry for not responding sooner!

The solution is simpler than you think: use double dashes to get the `th` route to activate as in `node index.js --th`

Minimist parses arguments letter by letter when you only specify a single dash before them and treats them as flags, while using double dashes reads the characters all the way to the end.

**Comment by 403-html** [comment]
Oh wow... thanks! So small thing...

**Comment by meszaros-lajos-gyorgy** [comment]
No worries, sorry again for taking this long to reply.
